<?php

/**
 * Implementation of hook_menu().
 */
function lytical_orphans_menu() {
  $items = array();

  $items['admin/content/orphans'] = array(
    'title' => 'Orphans',
    'page callback' => 'imce_user_page',
    'access arguments' => TRUE,
    'file' => 'lytical_orphans.page.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  return $items;
}

/**
 * Implements hook_views_api
 */
function lytical_orphans_views_api()
{
  return array(
    'api' => 3,
  );
}

